repos:
  # Prettier for code formatting (JS, TS, JSON, CSS, etc.)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.3
    hooks:
      - id: prettier
        entry: env PRETTIER_LEGACY_CLI=1 prettier
        files: \.(js|jsx|ts|tsx|json|css|scss|md)$

  # ESLint for linting JavaScript and TypeScript files
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.27.0  # update this to the latest version matching your setup
    hooks:
      - id: eslint
        name: ESLint
        args: ["--config", "eslint.config.mjs"]
        files: \.(js|jsx|ts|tsx)$

  # Common pre-commit hooks for text files, YAML, etc.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
