title: DSF Event Tracker
description: "A tool for tracking RuneScape events and scouts"
baseurl: ""
url: "https://dsfeventtracker.com"

# SEO settings
keywords: "RuneScape, events, scouts, tracking, DSF, Deep Sea Fishing, Alt1, toolkit, app, fishing, rs3, travelling merchant, discord"
author: "LukeHankey"

theme: jekyll-theme-slate
permalink: pretty

markdown: kramdown
highlighter: rouge

header_pages:
  - index.md
  - faq/index.md

github:
  is_project_page: false

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag