name: Build and deploy on push to main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Alt1 Dev

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Build stable version into dist/alt1/
        id: build_stable
        env:
          VERSION: ${{ steps.package-version.outputs.current-version }}
        run: |
<<<<<<< HEAD:.github/workflows/build-alt1-dev.yml
          git fetch --tags
          git checkout "v${{ steps.package-version.outputs.current-version }}"
          npm run build
          git switch -
=======
          set -e

          git fetch --tags

          TAG="v$VERSION"
          LATEST_TAG=$(git tag --sort=-v:refname | head -n1)

          if [ "$TAG" != "$LATEST_TAG" ]; then
            echo "${TAG} not found (latest is ${LATEST_TAG}), creating it…"
            git tag -a "$TAG" -m "chore(release): $TAG"
            git push origin "$TAG"
          else
            echo "Found existing tag ${TAG}"
          fi
>>>>>>> a7faf6f (Build combine workflows (#87)):.github/workflows/build_and_deploy.yml

          echo "Checking out ${TAG} and building stable…"
          git checkout "$TAG"
          npm run build
          git switch -

      - name: Build alt1-dev version
        run: npm run build:dev

      - name: Set Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Deploy to GitHub Pages
        run: |
          npx gh-pages -d dist --repo https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
